# -*- coding: utf-8 -*-
"""Avaliacao_4_Felipe_Romanholi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBleEgUOLwdTN2dnfHsVKuzZk0drHNEv

### ATIVIDADE PRÁTICA (Avaliação da Aula 04)


Esta atividade deve ser feita individualmente e a entrega deve ser feita com a sua cópia do Colab no Google Classroom.

## Desafio 04: Triagem de Despachos na *FlashLog Express*

A *FlashLog Express* opera centros de distribuição urbanos voltados para entregas no mesmo dia (*same-day delivery*). Durante o pico operacional, os pacotes chegam à esteira de expedição e passam por um sistema automatizado de triagem antes de serem alocados aos veículos de entrega.

O sistema de triagem segue um fluxo operacional rígido:

1. **Parâmetros Contratuais Fixos:** Existem limites operacionais (valor mínimo e máximo de frete cobrado por pacote) que são regulados por contrato e **não podem sofrer alterações** durante a execução do programa.
2. **Entrada e Ajustes de Fila:**
   * Os pedidos entram na esteira de despacho via teclado com `.append()`.
   * Um pacote prioritário (*Flash Ultra*) fura a fila e assume a primeira posição (`0`) com `.insert()`.
   * Para evitar excesso de peso no furgão, o último pacote da esteira é ejetado com `.pop()`.
3. **Organização e Auditoria:**
   * A lista é ordenada crescentemente com `.sort()`.
   * As métricas do lote são auditadas com `len`, `sum` e `max`.
4. **Classificação Automatizada (Estrutura de Decisão):**
   * Ao emitir a folha de manifesto com `enumerate`, o sistema avalia cada pacote com `if/else`: se o valor for menor que a tarifa máxima contratual da tupla, a entrega é classificada como **`"PADRÃO"`**; caso atinja ou supere esse teto, é sinalizada como **`"TARIFA PREMIUM"`**.

---

### Requisitos do Programa

#### 1. Blindagem de Parâmetros Contratuais (Tupla)
* Crie uma **tupla** chamada `limites_tarifa` contendo o valor mínimo e o valor máximo de frete: `(15.0, 50.0)`.
* Realize o **desempacotamento (*unpacking*)** da tupla nas variáveis `tarifa_min` e `tarifa_max`.
* Exiba na tela os valores carregados formatados em duas casas decimais com o *:.2f*.

#### 2. Fluxo Dinâmico na Esteira (Lista e Métodos)
* Crie a lista vazia `esteira = []`.
* Usando um laço `for` com `range`, colete via teclado o frete (em R$) de **3 pacotes convencionais** e insira cada um com `.append()`.
* **Inserção prioritária:** Insira um frete expresso de `R$ 20.00` no topo da fila (índice `0`) com `.insert()`.
* **Ejeção de carga:** Remova o último pacote da fila com `.pop()`, guarde o valor na variável `pacote_retido` e exiba-o no terminal.
* **Organização:** Ordene a esteira em ordem crescente com `.sort()`.

#### 3. Auditoria e Manifesto com Estrutura de Decisão
* Calcule e exiba a quantidade final de pacotes (`len`), o faturamento total da rota (`sum`) e a maior tarifa do lote (`max`).
* Percorra a lista com `for` e `enumerate(..., start=1)`:
  * **Estrutura de Decisão (`if/else`):**
    * Se a tarifa atual for **menor** que `tarifa_max`, a classificação será `"PADRÃO"`.
    * Senão, a classificação será `"TARIFA PREMIUM"`.
  * Exiba o resultado de cada item no formato: `Entrega #X: R$ YY.YY -> CLASSIFICAÇÃO`.
"""

# ==============================================================================
# ATIVIDADE PRÁTICA INDIVIDUAL - AULA 04
# Nome do(a) Estudante: [Felipe Romanholi]
# ==============================================================================

# Criando uma tupla chamada

limites_tarifa = (15.50, 50.0)

tarifa_min, tarifa_max = limites_tarifa

print(f"Tarifa mínima: R$ {tarifa_min:.2f}")
print(f"Tarifa máxima: R$ {tarifa_max:.2f}")

esteira = []

for i in range(1, 4):
  valor_frete = float(input(f"Digite o valor do frete para o pacote {i}: R$ "))
  esteira.append(valor_frete)

esteira.insert (0, 20.0)

pacote_retido = esteira.pop()

print(f"Pacote retido: R$ {pacote_retido:.2f}")

esteira.sort()

print()

print(f"Esteira ordenada: {[f'R$ {val:.2f}' for val in esteira]}")


quantidade_final = len(esteira)
faturamento_total = sum(esteira)
maior_tarifa = max(esteira)

print()
print("Relatório Final")
print(f"Quantidade final de pacotes: {quantidade_final}")
print(f"Faturamento total da rota: R$ {faturamento_total:.2f}")
print(f"Maior tarifa do lote: R$ {maior_tarifa:.2f}")

print()

print("Manifesto")

for id, tarifa in enumerate(esteira, start=1):
  if tarifa < tarifa_max:
    classificacao = "PADRÃO"
  else:
    classificacao = "TARIFA PREMIUM"
  print(f"Entrega #{id}: R$ {tarifa:.2f} {classificacao}")